version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: docker/tests.dockerfile
    volumes:
      - .:/opt/hubot-alerts
    restart: "no"
  hubot:
    build:
      context: .
      dockerfile: docker/hubot.dockerfile
    depends_on:
      - tests
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/hubot-alerts
    environment:
      HUBOT_SHIFTS: APJ=23:00-07:00,EMEA=07:00-15:00,AMS=15:00-23:00
  redis:
    image: redis:alpine
