version: '3'
services:
  tests:
    image: node:alpine
    working_dir: /opt/hubot-alerts
    command: sh -c 'npm install && npm test'
    volumes:
      - .:/opt/hubot-alerts
    restart: "no"
  hubot:
    build:
      context: .
      dockerfile: hubot-docker/Dockerfile
    depends_on:
      - tests
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/opt/hubot-alerts
    environment:
      HUBOT_SHIFTS: APJ=23:00-07:00,EMEA=07:00-15:00,AMS=15:00-23:00
  redis:
    image: redis:alpine
